name: Build on Windows

on: [push, pull_request, workflow_dispatch]

jobs:
  
  buildWindows:
    continue-on-error: true
    strategy:
      matrix:
        arch: [x64, x86, x64_arm64, x64_arm]
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }}
        cd wingui
        nmake UTF8=Y DLL=Y -f Makefile.vc demos
        cd ..\wincon
        nmake DLL=Y -f Makefile.vc demos
        cd ..\vt
        nmake CHTYPE_32=Y -f Makefile.vc demos
      shell: cmd
