name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  buildUbuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
         cd vt
         make demos
         cd ../fb
         make UTF8=Y demos
  buildOSX:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: make
      run: |
         cd vt
         make CLANG=Y demos
